config/routes.rb
Rails.application.routes.draw do
  

  namespace :cxpt do
    resources :mnews
    get 'cate/:id' => 'passage#index',as: 'pcate'
    get 'passage/:id' => 'passage#show',as: 'pshow'
    get 'index/index'
  end

  root 'cxpt/index#index'

  get 'api/professions'

  scope module: 'index' do
    get 'index/index'

    get 'news/' => 'news#index',as:'news_index'
    get 'news/:id' => 'news#show',as:'news'
    get 'news/:id/summary' => 'news#summary', defaults: {format: :json}

    get 'login/' => 'session#index'
    post 'login/' => 'session#create'
    delete 'logout' => 'session#logout',as:'logout'
    get 'login/forgot' => 'session#forgot'
    get 'login/regist' => 'session#regist'
    post 'login/regist' => 'session#regist_handler'
    get 'login/login'=>'session#login',as: 'login_box'

    get 'contest' => 'contest#index'
    get 'contest/:id' => 'contest#detail',as:'contest_detail'
    get 'contest/:id/confirm' => 'contest#confirm',as:'contest_confirm'

    get 'user/index'
    get 'user/email_checked' => 'user#email_checked'
    get 'user/email_checked_handler' => 'user#email_checked_handler'

  end

  
  namespace :manage do
    get '/vcode' => 'session#vcode',format: :png
    resources :admins 
    resources :roles
    resources :nodes,only: [:index]
    resources :configs,only: [:index,:edit,:update]
    resources :contests do 
      delete 'recover' => 'contests#recover'
    end

    resources :competes do
      resources :sections, except:[:index] do
        resources :xforms,except:[:index]
      end
    end

    get 'news/news_list'
    resources :news do
      delete 'recover'
      delete 'hard_delete'
    end
    resources :professions,except: [:new,:show]
    resources :students
    get '/'=> 'index#index'
    get  '/login'=>'session#index',as:'login'
    post '/login'=>'session#create'
    delete '/logout'=>'session#logout',as:'logout'

    get 'index/index'
    get 'index/dashboard'

    get 'self/index'
    post 'self/update'
  end
  mount Ckeditor::Engine => '/ckeditor'

end

app/controllers/index/session_controller.rb
class Index::SessionController < IndexController
  '''
    index控制器用于显示用户登录失败后的页面，会给用户失败的错误信息，以及登陆框、忘记密码等按钮。
  '''
  def index
    # render layout: false
  end

  '''
    create控制器用于在用户登录时处理表单数据，与系统内的数据对比，产生登录结果。同时应当在session中产生用户登录标志信息。登录成功跳转到index_student#index,失败就是sessio#index
  '''
  def create
    #判断用户名密码是否在数据库中存在
    if index_student = Manage::Student.auth(params[:stuid],params[:password])
        student_login(index_student)
        redirect_to user_index_path
    else
      #密码不正确或用户名不存在
      redirect_to login_url,:alert => "不正确的用户名/密码"
    end
  end

  '''
    用于显示登陆框
  '''
  def login
  end

  '''
    logout控制器用于在用户退出登录时从session中清除用户登录标志信息，跳转到首页
  '''
  def logout
    student_logout
    redirect_to index_index_path
  end

  '''
    用户忘记密码的页面
  '''
  def forgot

  end
  
  '''
    用户注册页面，只显示填表信息
  '''
  def regist
    @index_student = Manage::Student.new
    @professions = Manage::Profession.tree_view
  end

  '''
    接收用户注册信息，判断合法性，从而创建用户。
  '''
  def regist_handler
    @index_student = Manage::Student.new(index_student_params)
    @professions = Manage::Profession.tree_view

    respond_to do |format|
      if @index_student.save
        student_login(@index_student)
        format.html { redirect_to user_index_path, notice: '用户创建成功' }
        format.json { render :show, status: :created, location: @index_student }
      else
        format.html { render :regist }
        format.json { render json: @index_student.errors, status: :unprocessable_entity }
      end
    end
  end


private
  def index_student_params
      params.require(:manage_student).permit(:stuid, :name, :pwd, :email, :phone, :grade, :avatar)
  end
end

app/views/index/session/_login_box.html.erb
<div class="dialog-box">
  <h3>登录</h3>
  <div class="dialog-close" onclick="close_login_box()">&times;</div>
  <div id="top_frame">
    <div id="login_form">
      <%= form_tag login_path,name: "form" do %>
        <% if flash[:alert] %>
            <div class="alert alert-danger"><%= flash[:alert] %></div>
        <% else %>
            <div class="alert_placeholder"></div>
        <% end %>
        <ul>
          <li>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><i class="glyphicon glyphicon-user"></i></div>
                <%= text_field_tag :stuid,params[:stuid],class: "input-item input-username",placeholder: "请输入用户名","data-toggle"=> "popover",autofocus: true,title:"","data-content"=>"用户名不能为空" %>
              </div>
            </div>
          </li>
          <li>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></div>
                <%= password_field_tag :password,params[:password],class: "input-item input-pwd",placeholder: "请输入密码","data-toggle"=> "popover",title:"","data-content"=>"密码不能为空" %>
              </div>
            </div>
          </li>
<!--               <li>
            <input type="text" placeholder="验证码" class="input-item validate-code input-secure">
            <div class="validate-img"><img src="" alt=""></div>
              <span class="validate-word"> 看不清楚？<br/>换一张</span>
              <p class="color-red pop-warning"></p>
          </li>
          <li class="clear"></li> -->
        </ul>
        <div class="input-line">
            <label><input type="checkbox">记住我</label>
            <%= link_to '忘记密码',login_forgot_url,class:'forgot-pwd' %>
        </div> 
        <%= submit_tag "登录",class: "btn btn-block btn-primary" %>
      <% end %> 
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/index/session/create.html.erb
<h1>Index::Session#create</h1>
<p>Find me in app/views/index/session/create.html.erb</p>

app/views/index/session/forgot.html.erb
<h1>Index::Session#forgot</h1>
<p>Find me in app/views/index/session/logout.html.erb</p>

app/views/index/session/index.html.erb
<h1>用户登录</h1>
    <div id="top_frame">
        <div id="login_form">
            <%= form_tag login_path,name: "form",class:"form-inline" do %>
                    <% if flash[:alert] %>
                        <div class="alert alert-danger"><%= flash[:alert] %></div>
                    <% else %>
                        <div class="alert_placeholder"></div>
                    <% end %>
                    <%= text_field_tag :stuid,params[:stuid],class: "form-control login-input",placeholder: "请输入用户名","data-toggle"=> "popover",autofocus: true,title:"","data-content"=>"用户名不能为空" %>
                    <%= password_field_tag :password,params[:password],class: "form-control login-input",placeholder: "请输入密码","data-toggle"=> "popover",title:"","data-content"=>"密码不能为空" %>
                    <%= submit_tag "登录",class: "btn btn-success login-submit" %>
                    <%= link_to '忘记密码',login_forgot_url,class:'btn btn-default col-xs-12' %>
            <% end %> 
        </div>
    </div>

app/views/index/session/login.js.erb
$('#login-pop').html("<%= escape_javascript(render 'login_box') %>");
$('#black-layer').fadeIn();
$('#login-pop').fadeIn();

app/views/index/session/logout.html.erb
<h1>Index::Session#logout</h1>
<p>Find me in app/views/index/session/logout.html.erb</p>

app/views/index/session/regist.html.erb
<div class="container">
  <div class="page-header">
    <h2>注册账号</h2>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div class="flow current">
        <div class="order">1</div><span>填写基本信息</span>
      </div>
      <div class="flow">
        <div class="order">2</div><span>验证邮箱</span>
      </div>
      <div class="flow">
        <div class="order">3</div><span>上传头像</span>
      </div>
    </div>
    <div class="col-md-9">
      <%= form_for(@index_student,:html => {:class=>'regist-form'} , url: login_regist_path)  do |f| %>
        <%= form_errors(@index_student) %>
        
        <div class="col-md-5">
          <div class="form-group">
            <%= f.label :stuid %>
            <%= f.text_field :stuid,data:{validator:'^\d{10}$',message:"学号必须为10位数字"},placeholder:"10位数字" %>
          </div>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name,data:{validator:'^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]){2,5}$',message:"2-5个中文字符"},placeholder:"2-5个中文字符" %>
          </div>
          <div class="form-group">
            <%= f.label :pwd %>
            <%= f.password_field :pwd,data:{validator:'\w{8,}',message:"长度至少为8位"},placeholder:"密码至少8位" %>
          </div>
          <div class="form-group">
            <label for="pwd_confirmation">密码确认</label>
            <input id="pwd_confirmation" name="manage_student[pwd_confirmation]" type="password" placeholder="请再输一遍密码" data-message="密码不一致">
          </div>
          <div class="form-group">
            <%= f.label :profession %>
            <%= f.select :profession,option_groups_from_collection_for_select(@professions,:child,:name, :id, :name),include_blank: true %>
          </div>
          <div class="form-group">
            <%= f.label :grade %>
            <%= f.text_field :grade,data:{validator:'\d{2}',message:"应当为2位数字"},placeholder:"2位数字" %>
          </div>
          <div class="form-group">
            <%= f.label :phone %>
            <%= f.text_field :phone,data:{validator:'\d{11}',message:"应当为11位数字"},placeholder:"11位手机号码" %>
          </div>
          <%= f.submit '确认注册', class:"btn btn-primary btn-lg btn-block",onclick:"return checkform()" %>
        </div>
        

<!--       <tr>
              <td><%= f.label :email %></td>
              <td><%= f.text_field :email,class:"form-control" %></td>
              <td></td> 
            </tr> -->
            
<!-- <tr>
              <td><%= f.label :avatar %></td>
              <td><%= f.file_field :avatar,class:"form-control" %></td>
              <td></td> 
            </tr> -->

      <% end %>
    </div>
  </div>
    
</div>