config/routes.rb
Rails.application.routes.draw do
  

  namespace :cxpt do
    resources :mnews
    get 'cate/:id' => 'passage#index',as: 'pcate'
    get 'passage/:id' => 'passage#show',as: 'pshow'
    get 'index/index'
  end

  root 'cxpt/index#index'

  get 'api/professions'

  scope module: 'index' do
    get 'index/index'

    get 'news/' => 'news#index',as:'news_index'
    get 'news/:id' => 'news#show',as:'news'
    get 'news/:id/summary' => 'news#summary', defaults: {format: :json}

    get 'login/' => 'session#index'
    post 'login/' => 'session#create'
    delete 'logout' => 'session#logout',as:'logout'
    get 'login/forgot' => 'session#forgot'
    get 'login/regist' => 'session#regist'
    post 'login/regist' => 'session#regist_handler'
    get 'login/login'=>'session#login',as: 'login_box'

    get 'contest' => 'contest#index'
    get 'contest/:id' => 'contest#detail',as:'contest_detail'
    get 'contest/:id/confirm' => 'contest#confirm',as:'contest_confirm'

    get 'user/index'
    get 'user/email_checked' => 'user#email_checked'
    get 'user/email_checked_handler' => 'user#email_checked_handler'

  end

  
  namespace :manage do
    get '/vcode' => 'session#vcode',format: :png
    resources :admins 
    resources :roles
    resources :nodes,only: [:index]
    resources :configs,only: [:index,:edit,:update]
    resources :contests do 
      delete 'recover' => 'contests#recover'
    end

    resources :competes do
      resources :sections, except:[:index] do
        resources :xforms,except:[:index]
      end
    end

    get 'news/news_list'
    resources :news do
      delete 'recover'
      delete 'hard_delete'
    end
    resources :professions,except: [:new,:show]
    resources :students
    get '/'=> 'index#index'
    get  '/login'=>'session#index',as:'login'
    post '/login'=>'session#create'
    delete '/logout'=>'session#logout',as:'logout'

    get 'index/index'
    get 'index/dashboard'

    get 'self/index'
    post 'self/update'
  end
  mount Ckeditor::Engine => '/ckeditor'

end

app/models/cxpt.rb
module Cxpt
  def self.table_name_prefix
    'cxpt_'
  end
end

app/models/cxpt/cate.rb
class Cxpt::Cate < ActiveRecord::Base
  has_many :newses, :class_name => 'Cxpt::Mnews',foreign_key: 'cxpt_cate_id'
  has_many :children,class_name: 'Cxpt::Cate',foreign_key: "pid"
  belongs_to :parent, class_name: 'Cxpt::Cate',foreign_key: "pid"

  def self.all_cates
    [["未分类", nil]]+select("name,id").collect{|r|[r.name,r.id]}
  end

  # 输出树形的cate列表
  def self.tree_view
    cache = Cache.new('cxpt')
    c = cache[:cate_tree_cache]
    return c if c

    result = []
    parent = self.select(:id,:name,:display).where('pid=0').all
    parent.each do |x|
      tmp = {name: x.name , display: x.display, id: x.id, child: []}
      x.child = x.children.select(:id,:name,:display).load
      result << x
    end
    cache[:cate_tree_cache] = result
    result
  end

  def index_list
    newses.where('is_draft=false and publish_at<?',Time.now).select(:id,:title,:publish_at)
  end

  def child=(obj)
    @child = obj
  end
  def child
    @child || []
  end

  def display_text
    rule = {
        :image   => '图片新闻',
        :list    => '文字新闻',
        :passage => '文章页',
        :gallery => '展示页面'
    }
    rule[display.to_sym]
  end

  def self.get_by_id(id)
    if id
      find(id)
    else
      self.new(name:'未分类')
    end
  end


end

app/models/cxpt/mnews.rb
class Cxpt::Mnews < ActiveRecord::Base
  self.table_name = "cxpt_news"
  belongs_to :cate, :class_name => 'Cxpt::Cate',foreign_key: 'cxpt_cate_id'
  validates_length_of :title,minimum: 5
  validates_length_of :content,maximum: 60000

  mount_uploader :cover, CxptNewsCoverUploader


  before_save :set_summary_and_pure_content

  def set_summary_and_pure_content
    if self.content
      self.summary=self.content.gsub(/<\/?.*?>/,'').gsub(/&\w+;/,' ').gsub(/\s+/,' ')
    end
  end


  def self.published
    self.where('publish_at < ?',Time.now).where(is_draft: false)
  end

  def cate_name
    if cxpt_cate_id
      name=Cxpt::Cate.find(cxpt_cate_id).name
    else
      name="未分类"
    end
    name
  end

  def self.init_passage_news(cate)
    Cxpt::Mnews.create do |x|
      x.title = cate.name
      x.is_draft = false
      x.publish_at = Time.now
      x.cxpt_cate_id = cate.id
      x.content = ''
    end
  end

  def self.news_with_cover
    image_cates = Cxpt::Cate.where(display: 'image').select(:id).load
    image_cate_ids = image_cates.collect {|x| x.id}
    self.where('is_draft = 0 and publish_at < ?',Time.now).where(cxpt_cate_id: image_cate_ids).order(publish_at: :desc)
  end
end

app/controllers/cxpt/index_controller.rb
class Cxpt::IndexController < CxptController
  def index
    
    @news_with_cover = Cxpt::Mnews.news_with_cover.limit(5).select(:id,:title,:cover)

    @sys_intro = Cxpt::Mnews.where(title: '实验室简介').first

    @tzgg = Cxpt::Cate.where(name:'通知公告').first.index_list.limit(8)
    @cxdt = Cxpt::Cate.where(name:'创新动态').first.index_list.limit(8)
    @jxjh = Cxpt::Cate.where(name:'教学计划').first.index_list.limit(8)

    @cxcg = Cxpt::Cate.where(name:'创新作品').first.newses.where(is_draft:false).select(:id,:title,:cover).limit(8)
  end
end

app/controllers/cxpt/mnews_controller.rb
class Cxpt::MnewsController < ManageController
  before_action :set_cxpt_mnews, only: [:show, :edit, :update, :destroy]

  # GET /cxpt/mnews
  # GET /cxpt/mnews.json
  def index
    @cxpt_mnews = Cxpt::Mnews.select('left(summary, 300) as summary').select(:id,:title, :author, :publish_at, :view_count,:cxpt_cate_id,:is_draft).all
    @cate = Cxpt::Cate.all_cates
    @cate_tree = Cxpt::Cate.tree_view
  end

  # GET /cxpt/mnews/1
  # GET /cxpt/mnews/1.json
  def show
    p @cxpt_mnews.cate
  end

  # GET /cxpt/mnews/new
  def new
    @cate = Cxpt::Cate.get_by_id(params[:cate])
    set_view_stats

    # 如果是文章页应当直接跳转到文章的对应页面
    if @cate.display == 'passage'
      # 首先寻找是否已经存在标题为cate.name的文章
      passage = @cate.newses.where('title = ?',@cate.name).select(:id).first
      # 如果不存在就新建一个
      passage ||= Cxpt::Mnews.init_passage_news(@cate)
      # 如果最后创建成功了
      if passage
        logger.info passage.to_json
        redirect_to edit_cxpt_mnews_url(passage.id)
      else
        redirect_to :index, flash: '初始化文章失败！'
      end
    else
      @cxpt_mnews = Cxpt::Mnews.new(publish_at: Time.now, cxpt_cate_id: @cate.id)
    end
  end

  # GET /cxpt/mnews/1/edit
  def edit
    @cate = @cxpt_mnews.cate
    set_view_stats

  end

  # POST /cxpt/mnews
  # POST /cxpt/mnews.json
  def create
    @cate = Cxpt::Cate.get_by_id(params.require(:cxpt_mnews)[:cxpt_cate_id])
    @cxpt_mnews = Cxpt::Mnews.new(cxpt_mnews_params)
    set_view_stats
    respond_to do |format|
      if @cxpt_mnews.save
        format.html { redirect_to @cxpt_mnews, notice: '文章添加成功.' }
        format.json { render :show, status: :created, location: @cxpt_mnews }
      else
        format.html { render :new }
        format.json { render json: @cxpt_mnews.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cxpt/mnews/1
  # PATCH/PUT /cxpt/mnews/1.json
  def update
    @cate = @cxpt_mnews.cate
    set_view_stats
    respond_to do |format|
      if @cxpt_mnews.update(cxpt_mnews_params)
        format.html { redirect_to @cxpt_mnews, notice: '信息已更新' }
        format.json { render :show, status: :ok, location: @cxpt_mnews }
      else
        format.html { render :edit }
        format.json { render json: @cxpt_mnews.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cxpt/mnews/1
  # DELETE /cxpt/mnews/1.json
  def destroy
    @cxpt_mnews.destroy
    respond_to do |format|
      format.html { redirect_to cxpt_mnews_index_url, notice: '删除成功' }
      format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cxpt_mnews
      @cxpt_mnews = Cxpt::Mnews.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cxpt_mnews_params
      param=params.require(:cxpt_mnews).permit(:title, :author, :content, :is_draft, :publish_at,:cxpt_cate_id, :cover)
      if params[:commit] == "存为草稿"
        param[:is_draft] = true
      else
        param[:is_draft] = false
      end
      param
    end
  def set_view_stats
    stats = {title: true, content: 'full', author: false, publish_at: true, is_draft: false, image_uploader: false}
    display = @cate.display
    if display == 'passage'
      stats.merge!({title: false, publish_at: false})
    elsif display == 'gallery'
      stats.merge!({content: 'mini', publish_at: false, image_uploader: true})
    elsif display == 'image'
      stats.merge!({author: true, is_draft: true, image_uploader: true})
    else
      stats.merge!({author: true, is_draft: true})
    end
    @dopt = stats 
  end
end

app/controllers/cxpt/passage_controller.rb
class Cxpt::PassageController < CxptController
  def index
    @cate = Cxpt::Cate.where(name: params[:id]).first
    if @cate.display == 'passage'
      @p = @cate.newses.first
      redirect_to cxpt_pshow_url(@p) if @p
    end
    if @cate.pid == 0
      child = @cate.children.first
      redirect_to cxpt_pcate_url(child.name)
    end
    @ancestor = @cate.parent
    @passages = @cate.newses.select(:id,:title,:summary,:cover,:publish_at,:cxpt_cate_id).where(is_draft: false).page(params[:page])

    render :index_image if @cate.display == 'image'
    render :index_gallery if @cate.display == 'gallery'
  end

  def show
    @passage = Cxpt::Mnews.find(params[:id])
    @passage.increment!(:view_count)
    @cate = @passage.cate
    @ancestor = @cate.parent
  end
end

app/controllers/cxpt_controller.rb
class CxptController < ApplicationController
  before_action :set_navs

  def set_navs
    @nav = YAML.load(File.read("config/exts/cxpt_nav.yml"))
    @hot_passages = Cxpt::Mnews.published.select(:id,:title,:view_count).order(view_count: :desc).limit(8)
  end

end

app/helpers/cxpt/index_helper.rb
module Cxpt::IndexHelper
  def cxpt_nav_link(n,config={})
    if n['controller']
      link_to n['text'],{controller: 'cxpt/'+n['controller'], action: n['action']},config
    else
      link_to n['text'],cxpt_pcate_url(n['text']),config
    end
  end
end

app/helpers/cxpt/mnews_helper.rb
module Cxpt::MnewsHelper
  def mnews_status_label(news)
    #信息在草稿箱中
    if news.is_draft
      tag=bs_label_tag('草稿','default')
      #信息未发布
    elsif news.publish_at.nil? || news.publish_at < Time.now
      tag=bs_label_tag('已发布','success')
    elsif news.publish_at > Time.now
      tag=bs_label_tag('未发布','info')
    end
    tag
  end

  def mnews_cate_option(tree_obj)
    result = ''
    tree_obj.each do |p|
      result+=sprintf('<optgroup label="%s">',p.name)
      p.child.each do |c|
        type=c.display_text
        result+=sprintf('<option value="%d" data-subtext="%s">%s</option>',c.id,type,c.name)
      end
      result+='</optgroup>'
    end
    result.html_safe
  end
  def mnews_cate_option_with_all(tree_obj)
    result='<optgroup label="全选">' \
          +'<option value="0" data-subtext="">全选</option>' \
          +'</optgroup>'
    result+= mnews_cate_option(tree_obj)
    result.html_safe
  end
end

app/helpers/cxpt/passage_helper.rb
module Cxpt::PassageHelper
end

app/views/cxpt/mnews/_form.html.erb
<%= content_for :before_js do %>
<%= javascript_include_tag 'ckeditor/init' %>
<% end %>

<%= form_for(@cxpt_mnews,html:{class:"form-inline edit_form"}) do |f| %>
    <%= form_errors(@cxpt_mnews) %>
    <%= f.hidden_field :cxpt_cate_id %>
    <table class="table">

      <tr>
        <td width="15%"><%= f.label :title %></td>
        <td>
          <% if @dopt[:title]==true %>
          <%= f.text_field :title,class:'form-control',style:'width:60%' %>
          <% end %>
          <span class="label label-info">类别： <%= @cate.name %></span>
        </td>
      </tr>
      <% if @dopt[:image_uploader]==true %>
      <tr>
        <td><%= f.label :cover %></td>
        <td><%= f.file_field :cover %></td>
      </tr>
      <% end %>
      <tr>
        <td><%= f.label :content %></td>
        <td>
          <% if @dopt[:content]=='full' %>
            <%= f.cktext_area :content,:ckeditor => {:uiColor => '#efefef'} %>
          <% else %>
            <%= f.cktext_area :content,:ckeditor => {uiColor: '#efefef',toolbar: 'mini'} %>
          <% end %>
        </td>
      </tr>

      <% if @dopt[:author]==true %>
      <tr>
        <td><%= f.label :author %></td>
        <td><%= f.text_field :author,class:'form-control' %></td>
      </tr>
      <% end %>

      <% if @dopt[:publish_at]==true %>
      <tr>
        <td><%= f.label :publish_at %></td>
        <td colspan="3"><%= f.datetime_local_field :publish_at %></td>
      </tr>
      <% end %>

      <tr>
        <td></td>
        <td colspan="3">
          <%= f.submit "立即发布",class:"btn btn-success",id:"publish_button" %>
          <% if @dopt[:is_draft]==true %>
          <%= f.submit "存为草稿",class:"btn btn-primary" %>
          <% end %>
        </td>
      </tr>

    </table>
<% end %>

app/views/cxpt/mnews/edit.html.erb
<%= link_to '返回目录页',cxpt_mnews_index_path,class: 'btn btn-primary' %>
<div class="page-header">
  <h1>编辑“<%= @cxpt_mnews.title %>”</h1>
</div>
<%= render 'form' %>

app/views/cxpt/mnews/index.html.erb
<div class="page-header">
  <h2>创新平台文章管理</h2>

  <%= form_tag(new_cxpt_mnews_path, method: :get) do %>
      <%= select_tag :cate,mnews_cate_option(@cate_tree),class:'selectpicker',id:'new_passage_select' %>
      <button class="btn btn-success" id="new_passage_submit">添加新文章</button>
  <% end %>

</div>

<div ng-app="newsList">
  <div ng-controller="listController">
    <div class="filter_box">
      <h4>筛选</h4>
      <table class="table  table-condensed">
        <tr>
          <td>发布状态</td>
          <td>
            <label class="option"><input type="radio" value="已发布" ng-model="flt.status" name="status"> 已发布</label>
            <label class="option"><input type="radio" value="未发布" ng-model="flt.status" name="status"> 未发布</label>
            <label class="option"><input type="radio" value="草稿" ng-model="flt.status" name="status"> 草稿</label>
          </td>
          <td>发布类别</td>
          <td>
            <%= select_tag :ui_cate,mnews_cate_option_with_all(@cate_tree),class:'selectpicker' %>
          </td>
          <td>搜索</td>
          <td><input type="text" name="search" ng-model="flt.search" class="rounded_input" placeholder="标题/摘要"></td>
        </tr>
      </table>
    </div>
    <br>
    <table class="table table-condensed">
      <thead>
      <th>类别</th>
      <th>标题</th>
      <th width="50%">摘要</th>
      <th>发布日期</th>
      <th>浏览量</th>
      <th>状态</th>
      <th width="80px"></th>
      </thead>
      <tbody ng-init="getData()">
      <tr ng-repeat="item in dataset | select_panel:flt as results  ">
        <td>{{item.cate}}</td>
        <td>{{item.title}}</td>
        <td>
          <div class="summary_box">
            {{item.summary}}

          </div>
        </td>
        <td>{{item.publish_at | date:'yy-MM-dd'}}</td>
        <td>{{item.view_count}}</td>
        <td><span class="label label-{{item.stats.stl}}">{{item.stats.text}}</span></td>
        <td>
          <a ng-href="{{item.url}}" class="btn btn-info btn-sm"><%= fa_icon "info" %></a>
          <a ng-href="{{item.url}}/edit" class="btn btn-warning btn-sm"><%= fa_icon "pencil" %></a>
        </td>
      </tr>
      </tbody>
    </table>
    <div class="result_set_status">已找到{{results.length}}条，共{{dataset.length}}条</div>
  </div>
</div>


<%= content_for :before_js do %>
    <script>
        var news_list = angular.module('newsList',[]);
        news_list.controller('listController', function ($scope,$http){
            $scope.flt = {
                ui_cate_name:"全选",
                status:"已发布",
                search:""
            };

            $('#ui_cate').change(function(){
              var this_obj = $(this);
              var cate_id = this_obj.val();
              var cate_name = this_obj.find('option[value='+cate_id+']').html();
              $scope.flt.ui_cate_name = cate_name;
              $scope.$digest();
            });

            $scope.getData = function (){
                var data = $http.get('<%= cxpt_mnews_index_path(format: :json) %>',{cache: true});
                data.success(function (data){
                    var time_now = new Date();
                    for(key in data){
                        if(!data[key]["publish_at"]){
                            data[key]["stats"]={stl: "success",text:"已发布"};
                        }else{
                            data[key]["publish_at"] = new Date(data[key]["publish_at"]);
                            if(data[key].is_draft){
                                data[key]["stats"]={stl: "default",text:"草稿"};
                            }else if(data[key]["publish_at"]<time_now){
                                data[key]["stats"]={stl: "success",text:"已发布"};
                            }else if(data[key]["publish_at"]>time_now){
                                data[key]["stats"]={stl: "info",text:"未发布"};
                            }
                        }

                    }

                    $scope.dataset = data;
                });
                data.error(function (data){
                    alert("数据加载错误！");
                });
            };
        });
        news_list.filter('select_panel',function () {
            return function (items, flt){
                var result = [];
                var status = flt.status;
                var search_text = flt.search;
                for(i in items){
                    // 如果列表元素的状态与选中的状态相同
                    if(items[i].stats.text==status){
                        // 如果列表元素的类别在cate_arr中
                        if(flt.ui_cate_name === '全选' || flt.ui_cate_name==items[i].cate ){
                            // 如果有输入搜索词且在title或summary中出现
                            if(search_text != ""){
                                if(items[i].title.indexOf(search_text)>=0 || items[i].summary.indexOf(search_text)>=0){
                                    result.push(items[i]);
                                }
                            }else{
                                // 保存
                                result.push(items[i]);
                            }
                        }
                    }
                }
                return result;
            }
        });
    </script>
<% end %>

app/views/cxpt/mnews/new.html.erb
<%= link_to '返回目录页',cxpt_mnews_index_path,class: 'btn btn-primary' %>
<div class="page-header">
  <h1>添加新文章</h1>
</div>
<%= render 'form' %>

app/views/cxpt/mnews/show.html.erb
<%= link_to '返回目录页',cxpt_mnews_index_path,class: 'btn btn-primary' %>

<div class="page-header">
  <h2><%= @cxpt_mnews.title %> </h2>
</div>

<table class="table table-bordered">
  <tr>
    <td width="120px">当前状态</td>
    <td><%= mnews_status_label @cxpt_mnews %></td>
    <td>操作</td>
    <td>
      <%= link_to '编辑', edit_cxpt_mnews_path(@cxpt_mnews),class:"btn btn-warning" %>
      <%= link_to '删除', cxpt_mnews_path(@cxpt_mnews),method: :delete,class:"btn btn-danger" %>
    </td>
  </tr>
  <tr>
    <td>所属类别</td>
    <td><%= @cxpt_mnews.cate_name %></td>
    <td>作者</td>
    <td><%= @cxpt_mnews.author %></td>
  </tr>
  <tr>
    <td>封面图片</td>
    <td colspan="3"><%= image_tag @cxpt_mnews.cover %></td>
  </tr>
  <tr>
    <td>发布日期</td>
    <td><%= @cxpt_mnews.publish_at %></td>
    <td>浏览量</td>
    <td><%= @cxpt_mnews.view_count %></td>
  </tr>
  <tr>
    <td>创建日期</td>
    <td><%= @cxpt_mnews.created_at %></td>
    <td>最后修改日期</td>
    <td><%= @cxpt_mnews.updated_at %></td>
  </tr>
    <tr>
      <td>正文</td>
      <td colspan="3"><%= raw @cxpt_mnews.content %></td>
    </tr>

</table>