config/routes.rb
Rails.application.routes.draw do
  

  namespace :cxpt do
    resources :mnews
    get 'cate/:id' => 'passage#index',as: 'pcate'
    get 'passage/:id' => 'passage#show',as: 'pshow'
    get 'index/index'
  end

  root 'cxpt/index#index'

  get 'api/professions'

  scope module: 'index' do
    get 'index/index'

    get 'news/' => 'news#index',as:'news_index'
    get 'news/:id' => 'news#show',as:'news'
    get 'news/:id/summary' => 'news#summary', defaults: {format: :json}

    get 'login/' => 'session#index'
    post 'login/' => 'session#create'
    delete 'logout' => 'session#logout',as:'logout'
    get 'login/forgot' => 'session#forgot'
    get 'login/regist' => 'session#regist'
    post 'login/regist' => 'session#regist_handler'
    get 'login/login'=>'session#login',as: 'login_box'

    get 'contest' => 'contest#index'
    get 'contest/:id' => 'contest#detail',as:'contest_detail'
    get 'contest/:id/confirm' => 'contest#confirm',as:'contest_confirm'

    get 'user/index'
    get 'user/email_checked' => 'user#email_checked'
    get 'user/email_checked_handler' => 'user#email_checked_handler'

  end

  
  namespace :manage do
    get '/vcode' => 'session#vcode',format: :png
    resources :admins 
    resources :roles
    resources :nodes,only: [:index]
    resources :configs,only: [:index,:edit,:update]
    resources :contests do 
      delete 'recover' => 'contests#recover'
    end

    resources :competes do
      resources :sections, except:[:index] do
        resources :xforms,except:[:index]
      end
    end

    get 'news/news_list'
    resources :news do
      delete 'recover'
      delete 'hard_delete'
    end
    resources :professions,except: [:new,:show]
    resources :students
    get '/'=> 'index#index'
    get  '/login'=>'session#index',as:'login'
    post '/login'=>'session#create'
    delete '/logout'=>'session#logout',as:'logout'

    get 'index/index'
    get 'index/dashboard'

    get 'self/index'
    post 'self/update'
  end
  mount Ckeditor::Engine => '/ckeditor'

end

app/views/index/index/index.html.erb
<div class="typer">

</div>
<section class="slogan">
  <h2> &gt;
    <span id="typer-text" data-typer-targets="第三届蓝桥杯软件设计比赛开始报名了,第二届中国软件杯进入复赛阶段,ACM-ICPC亚洲邀请赛西安赛区将于周五进行"></span>
    <span id="typed-cursor">|</span>
  </h2>
</section>

<div id="first-eye" class="" >
  <div class="row">
  <div class="col-md-8">
    <div class=" lunbo-box shadow-box">
        <%= image_tag 'index/slogan.jpg' %>
      <div class="info">
        <h3>测试内容</h3>
        <p class="description">
          测试内容and测试内容测试内容and测试内容测试内容and测试内容 <br/>
          测试内容and测试内容测试内容and测试内容测试内容and测试内容 <br/>
          测试内容and测试内容测试内容and测试内容测试内容and测试内容 <br/>
          测试内容and测试内容测试内容and测试内容测试内容and测试内容 <br/>
          测试内容and测试内容测试内容and测试内容测试内容and测试内容 <br/>

        </p>
      </div>
    </div>
  </div>
  <div class="col-md-4 shadow-box" id="news">
    <div class="title">
      <h3>比赛资讯 <small>COMPETITION NEWS</small></h3>
    </div>
    <div class="news-list">
      <ul>
        <% @news.each do |item| %>
        <li><a href="<%= news_path(item.id) %>" title="<%= item.title %>" data-type="<%= item.contest %>"><%= item.title %> <span class="date"><%= date_mini item.publish_at %></span></a></li>
        <% end %>
      </ul>
    </div>
  </div>
  </div>
</div>


<div class="competition">
  <div class="header">
    <h2>赛事介绍</h2>
  </div>
</div>


<div class="container-fluid">
    <div class="main-content">
        <div class="row section-four">
            <div class="competition">
                <div class="competition-list">
                    <div class="nav-control competition-nav">
                        <div class="container">
                            <ul class="nav nav-pills tab-control col-md-8 col-md-offset-2">
                                <div class="row">
                                    <% @contests.each do |contest| %>
                                        <li class="col-xs-3"><a class="col-xs-12" href="#"><%= contest.name %></a></li>
                                    <% end %>
                                </div>

                            </ul>
                        </div>
                    </div>
                    <div class="flexslider white-box">
                        <div class="container">
                            <ul class="slides">  <!-- slides begin -->
<% @contests.each do |contest| %>
    <li>
    <div class="col-md-10 col-md-offset-1">
    <div class="competition-desc">
    <div class="row">
        <div class="competition-pic col-md-6">
            <%= image_tag contest.cover.url,style:"margin-top:0;margin-left:150px;max-height:200px" %>
        </div>
        <div class="col-md-6">
            <div class="competition-desc-title">
                <h2><%= contest.name %></h2>
            </div>
            <div class="competition-desc-content">
                <p><%= contest.summary %></p>
            </div>
          <%= link_to '查看详细介绍',contest_detail_path(contest),class:'btn btn-primary' %>
        </div>
    </div>
    </div>

    </div>
    </li>
<% end %>

                            </ul>  <!-- slides end -->
                        </div>
                    </div>
                </div> <!-- competition list end -->
            </div>
        </div>              
    </div>
</div>

<%= content_for :js do %>
<%= javascript_include_tag  "jquery.flexslider-min.js",'data-turbolinks-track' => true %>
<%= javascript_include_tag  "jquery.typer.js",'data-turbolinks-track' => true %>
<% end %>