config/routes.rb
Rails.application.routes.draw do
  

  namespace :cxpt do
    resources :mnews
    get 'cate/:id' => 'passage#index',as: 'pcate'
    get 'passage/:id' => 'passage#show',as: 'pshow'
    get 'index/index'
  end

  root 'cxpt/index#index'

  get 'api/professions'

  scope module: 'index' do
    get 'index/index'

    get 'news/' => 'news#index',as:'news_index'
    get 'news/:id' => 'news#show',as:'news'
    get 'news/:id/summary' => 'news#summary', defaults: {format: :json}

    get 'login/' => 'session#index'
    post 'login/' => 'session#create'
    delete 'logout' => 'session#logout',as:'logout'
    get 'login/forgot' => 'session#forgot'
    get 'login/regist' => 'session#regist'
    post 'login/regist' => 'session#regist_handler'
    get 'login/login'=>'session#login',as: 'login_box'

    get 'contest' => 'contest#index'
    get 'contest/:id' => 'contest#detail',as:'contest_detail'
    get 'contest/:id/confirm' => 'contest#confirm',as:'contest_confirm'

    get 'user/index'
    get 'user/email_checked' => 'user#email_checked'
    get 'user/email_checked_handler' => 'user#email_checked_handler'

  end

  
  namespace :manage do
    get '/vcode' => 'session#vcode',format: :png
    resources :admins 
    resources :roles
    resources :nodes,only: [:index]
    resources :configs,only: [:index,:edit,:update]
    resources :contests do 
      delete 'recover' => 'contests#recover'
    end

    resources :competes do
      resources :sections, except:[:index] do
        resources :xforms,except:[:index]
      end
    end

    get 'news/news_list'
    resources :news do
      delete 'recover'
      delete 'hard_delete'
    end
    resources :professions,except: [:new,:show]
    resources :students
    get '/'=> 'index#index'
    get  '/login'=>'session#index',as:'login'
    post '/login'=>'session#create'
    delete '/logout'=>'session#logout',as:'logout'

    get 'index/index'
    get 'index/dashboard'

    get 'self/index'
    post 'self/update'
  end
  mount Ckeditor::Engine => '/ckeditor'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>创新实验室管理系统</title>
  <%= stylesheet_link_tag    "bootstrap_ball", media: 'all' %>
  <%= stylesheet_link_tag    "index/common", media: 'all' %>
  <%= stylesheet_link_tag    params[:controller], media: 'all' %>
  <%= yield :css %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="<%= asset_path 'html5shiv.min.js' %>>"></script>
  <![endif]-->
</head>
<body>
<header>
  <nav>
    <ul class="links">
      <li class="active">
        <a href="<%= index_index_url %>">首 页</a>
      </li>
      <li>
        <a href="<%= contest_url %>"> 比赛列表</a>
      </li>
      <li><%= link_to "后台管理",manage_url %></li>
    </ul>
  </nav>
    <div id="logo"><a href="<%= index_index_url %>"><%= image_tag 'index/logo.png' %></a></div>
    <div id="userzone">
      <nav>
        <ul class="links user">
          <% if @student %>
              <li class="info">
                <a href="<%= user_index_path %>"><%= image_tag @student.avatar.url(:thumb_mini),width:30,height:30,id:"user-avatar" %> &nbsp;用户中心</a>
              </li>
              <li class="warning"><%= link_to "退出",logout_path,method: :delete %></li>
          <% else %>
              <li class="">
                <%= link_to '登录',login_box_url,remote: true %>
              </li>
              <li class="success"><a href="<%= login_regist_url %>">注册</a></li>
          <% end %>
        </ul>
      </nav>
    </div>

</header>

<div class="main">
    <div class="content container">
      <%= yield %>
    </div>  
</div>

<footer>
  <div class="copyright text-center">
    <div class="footer-logo">创新实验室</div>
    <p class="text">Copyright © 2013-4ever cxlab</p>
  </div>
</footer>

<!-- 用户登录浮动框 -->
<div id="login-pop" class="dialog" style="display:none"></div>
<div id="black-layer" style="display:none"></div>


</body>
<%= javascript_include_tag  "index/common" %>
<%= javascript_include_tag params[:controller] %>
<%= yield :js %>
</html>

app/views/layouts/cxpt.html.erb
<!DOCTYPE html>
<html lang="zh-cn">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= yield :title %>实验室项目</title>
  <link rel="shortcut icon" href="/favicon.ico" />
  <!-- Bootstrap -->
  <%= stylesheet_link_tag    'bootstrap_ball', media: 'all'%>
  <%= stylesheet_link_tag    'cxpt', media: 'all'%>
  <%= stylesheet_link_tag params[:controller]  %>
  <%= yield :css %>
  <%= csrf_meta_tags %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<div class="container">
  <div class="header">
    <div class="logo">
        <%= image_tag 'cxpt/hohai-university.png',height: '81px',width: '603px' %>
    </div>

  </div>
</div>
  <div class="nav">
    <div class="container">

        <ul>

          <% @nav.each do |n| %>
              <li>
                <%= cxpt_nav_link n,class:'parent' %>
                <% if n['children'] %>
                    <div class="child">
                      <% n['children'].each do |nc| %>
                          <%= cxpt_nav_link nc %>

                      <% end %>
                    </div>
                <% end %>
              </li>
          <% end %>
          <li>
            <%= link_to '比赛系统',index_index_url %>
          </li>


        </ul>
      </div>

  </div>

<div class="container" id="main-container">
  <div class="row">
    <div class="aside col-md-3">
        <%= yield :aside %>
      <div class="sidebar">
        <div class="title">热门文章</div>
      </div>
      <table class="table table-condensed">
        <% @hot_passages.each do |p| %>
            <tr>
              <td><%= link_to p.title,cxpt_pshow_url(p) %></td>
              <td><%= p.view_count %></td>
            </tr>
        <% end %>
      </table>
    </div>
    <div class="col-md-9">
      <div id="main">
        <%= yield :lunbo %>
        <%= yield %>
      </div>
    </div>

    <div class="clear"></div>
  </div>
  <hr/>
  <div class="text-center">
    版权所有 © 河海大学计算机与信息学院--信息工程创新实验中心, 2015－2015, all rights reserved
  </div>
</div>



<%= javascript_include_tag 'cxpt/common' %>
<%= javascript_include_tag params[:controller] %>
<%= yield :js %>
</body>
</html>

app/views/layouts/manage.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>后台管理</title>
  <%= stylesheet_link_tag    "bootstrap_ball", media: 'all' %>
  <%= stylesheet_link_tag    "manage/common", media: 'all' %>
  <%= stylesheet_link_tag    params[:controller], media: 'all' %>
  <%= yield :css %>
  <%= javascript_include_tag 'angular.min.js' %>
  <%= yield :before_js %>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
    <% unless notice.nil? %>
        <div class="alert alert-info">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= notice %>
        </div>
    <% end %>

    <%= yield %>
</div>

</body>
<%= javascript_include_tag 'application' %>
<%= javascript_include_tag  "manage/common" %>
<%= javascript_include_tag params[:controller] %>
<%= yield :js %>
</html>